### ISSUE TITLE
Issues deploying code in Chapter 6

### ISSUE THREAD

**Issue by mattwelke** [fourTheorem/ai-as-a-service#4]
I encountered some issues when reading Chapter 6 and deploying the code.

I decided not to do a pull request for these issues since not all of them have simple fixes and you may want to rearrange names of env vars instead of using the workaround I used to get the region env var in for it to run.

**Issue 1:**

Right before `6.6. Testing the Pipeline`, on page 27 of the current PDF, there is a deploy command. When I ran it I got an error:

```
Serverless Error ---------------------------------------
 
  An error occurred: TranslateEventSourceMappingKinesisC6ptransstream - Unrecognized event source, must be kinesis, dynamodb stream or sqs. Expected arn of format arn:aws:kinesis:us-east-1:111122223333:stream/my-stream (Service: AWSLambda; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: e3a2c3e3-9415-4edf-bdfc-070188f96e47).
```

The error message included `us-east-1` so I thought it might an issue with how the region was substituted.

I replaced `AWS_REGION` with `TARGET_REGION` in the `.env` file we're preparing and then it worked. My `.env` file included vars for Kinesis that looked like this after this change:

```
CHAPTER6_PIPELINE_TRANSLATE_STREAM_ARN=arn:aws:kinesis:${TARGET_REGION}:${AWS_ACCOUNT_ID}:stream/${CHAPTER6_PIPELINE_TRANSLATE_STREAM}
CHAPTER6_PIPELINE_SENTIMENT_STREAM_ARN=arn:aws:kinesis:${TARGET_REGION}:${AWS_ACCOUNT_ID}:stream/${CHAPTER6_PIPELINE_SENTIMENT_STREAM}
CHAPTER6_CLASSIFIER_NAME=chap6classifier
CHAPTER6_CLASSIFIER_ARN=arn:aws:comprehend:${TARGET_REGION}:${AWS_ACCOUNT_ID}:document-classifier/${CHAPTER6_CLASSIFIER_NAME}
```

**Issue 2:**

I ran `streamReader.js` where we're instructed to, and I got the following error:

```
ConfigError: Missing region in config
at Request.VALIDATE_REGION
```

That was the top of the stacktrace.

I found a solution here: https://stackoverflow.com/questions/47009074/configuration-error-missing-region-in-config-aws

I added this code:

```js
AWS.config.update({
  region: env.TARGET_REGION,
});
```

in `streamReader.js` after the requires but before the AWS SDK is called. It worked.

**Issue 3:**

I had the same problem in train-classifier.js later in the chapter when I ran `train.sh`. Solved the same way, adding the region override code. This script didn't use the `dotenv` library so I had to use `process.env` to access the target region.

```js
AWS.config.update({
  region: process.env.TARGET_REGION
})
```

I also had to add `export TARGET_REGION` to `train.sh` so that it would carry the env var through to the Node script. Then it ran properly.

I had to make this same change to `status.sh` and `check-status.js` to be able to run it.

**Issue 4:**

When deploying the `classify` service, I got an error:

```
Serverless Error ---------------------------------------
 
  Invalid variable reference syntax for variable env.CHAPTER6_DATA_ACCESS_ARN. You can only reference env vars, options, & files. You can check our docs for more info.
```

I examined the different `serverless.yml` files to compare them and noticed that this variable was being accessed with a period instead of a colon. I changed `env.` to `env:` in this service and then the deploy worked.

**Comment by pelger** [comment]
Many thanks for the detailed feedback. This has been corrected and incorporated into the text. Much appreciated!
